version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbit"
    ports:
    - 5672:5672

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - 27017:27017


  consumer:
    build: ./consumer
    container_name: "consumer"
    links:
        - mongodb
        - rabbitmq


