FROM python:3

RUN mkdir /task
WORKDIR /task

ADD . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
#
#CMD ["python3", "manage.py", "makemigrations"]
#CMD ["python3", "manage.py", "migrate"]
#CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]