version: "3.3"

services:

    db:
        image: postgres
    app:
        build: .
        container_name: "app"
        command: bash run.sh
        ports:
          - "8000:8000"
        depends_on:
          - db